[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.git
    | \.tox
    | build
    | dist
  )/
)
'''

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py35,py36,py37

[testenv]
deps = pytest == 5.3.5
commands = pytest
"""